<!doctype html>
<html>
  <head>
    <title>LGSF Dashboard</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <link rel="shortcut icon" href="https://democracyclub.org.uk/static/images/logo_icon.png">
  </head>
  <body>
    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  


  <h2 id="2022-04-26-12-35">2022-04-26</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>11 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-26 12:35:22.237692</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-26 12:35:33.543819</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:35:22] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:230
           Getting all files in NTL...                               base.py:182
[12:35:23] Getting all files in NTL/json...                          base.py:182
           ...found 65 files in NTL/json                             base.py:198
           Getting all files in NTL/raw...                           base.py:182
           ...found 65 files in NTL/raw                              base.py:198
           ...found 131 files in NTL                                 base.py:198
           Deleting batch no. 1 consisting of 100 files              base.py:207
[12:35:24] Deleting batch no. 2 consisting of 31 files               base.py:207
[12:35:25] ...data deleted.                                          base.py:237
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:42
           mx/GetCouncillorsByWard                                              
[12:35:30] Committing batch 1 consisting of 92 files                 base.py:265
[12:35:32] Committing batch 2 consisting of 38 files                 base.py:265
[12:35:33] Finished attempting to scrape: NTL                        base.py:315
</pre>
  

  


  <h2 id="2022-04-25-12-39">2022-04-25</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>10 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-25 12:39:23.343394</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-25 12:39:33.727489</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:39:23] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:230
[12:39:24] Getting all files in NTL...                               base.py:182
           Getting all files in NTL/json...                          base.py:182
           ...found 65 files in NTL/json                             base.py:198
           Getting all files in NTL/raw...                           base.py:182
           ...found 65 files in NTL/raw                              base.py:198
           ...found 131 files in NTL                                 base.py:198
           Deleting batch no. 1 consisting of 100 files              base.py:207
[12:39:25] Deleting batch no. 2 consisting of 31 files               base.py:207
[12:39:26] ...data deleted.                                          base.py:237
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:42
           mx/GetCouncillorsByWard                                              
[12:39:30] Committing batch 1 consisting of 92 files                 base.py:265
[12:39:32] Committing batch 2 consisting of 38 files                 base.py:265
[12:39:33] Finished attempting to scrape: NTL                        base.py:315
</pre>
  

  


  <h2 id="2022-04-24-19-29">2022-04-24</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-24 19:29:33.758262</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-24 19:29:42.431489</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[19:29:33] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:230
[19:29:34] Getting all files in NTL...                               base.py:182
           ...found 1 files in NTL                                   base.py:198
           Deleting batch no. 1 consisting of 1 files                base.py:207
[19:29:35] ...data deleted.                                          base.py:237
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:42
           mx/GetCouncillorsByWard                                              
[19:29:39] Committing batch 1 consisting of 92 files                 base.py:265
[19:29:41] Committing batch 2 consisting of 38 files                 base.py:265
[19:29:42] Finished attempting to scrape: NTL                        base.py:315
</pre>
  

  


  <h2 id="2022-04-23-12-01">2022-04-23</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-23 12:01:57.730478</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-23 12:02:00.186984</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 174, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 191, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:01:57] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
[12:01:58] Getting all files in NTL...                               base.py:180
           ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[12:01:59] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[12:02:00] Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-22-11-52">2022-04-22</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-22 11:52:10.258264</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-22 11:52:12.706630</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 174, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 191, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:52:10] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
[11:52:11] Getting all files in NTL...                               base.py:180
           ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[11:52:12] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-21-11-40">2022-04-21</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-21 11:40:14.261591</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-21 11:40:16.708302</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:40:14] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
           Getting all files in NTL...                               base.py:180
[11:40:15] ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[11:40:16] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-20-11-23">2022-04-20</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-20 11:23:58.170753</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-20 11:24:01.273159</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:23:58] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
           Getting all files in NTL...                               base.py:180
[11:23:59] ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[11:24:00] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
[11:24:01] HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-19-12-11">2022-04-19</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-19 12:11:56.019256</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-19 12:11:58.482441</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:11:56] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
           Getting all files in NTL...                               base.py:180
           ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[12:11:58] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-18-14-17">2022-04-18</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-18 14:17:39.265646</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-18 14:17:41.702741</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:17:39] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
           Getting all files in NTL...                               base.py:180
[14:17:40] ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[14:17:41] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-17-11-22">2022-04-17</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-17 11:22:27.083650</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-17 11:22:29.472356</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:22:27] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
           Getting all files in NTL...                               base.py:180
[11:22:28] ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[11:22:29] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-16-14-40">2022-04-16</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-16 14:40:57.971933</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-16 14:41:00.111801</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:40:57] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
[14:40:58] Deleting existing data...                                 base.py:228
           Getting all files in NTL...                               base.py:180
           ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[14:40:59] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[14:41:00] Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-15-13-00">2022-04-15</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-15 13:00:41.024927</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-15 13:00:44.800203</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:00:41] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
[13:00:42] Getting all files in NTL...                               base.py:180
[13:00:43] ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[13:00:44] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-14-17-54">2022-04-14</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-14 17:54:17.679866</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-14 17:54:19.993548</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[17:54:17] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
[17:54:18] Getting all files in NTL...                               base.py:180
           ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[17:54:19] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-13-13-57">2022-04-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-13 13:57:22.092236</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-13 13:57:24.439847</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:57:22] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:27
           Deleting existing data...                                 base.py:228
           Getting all files in NTL...                               base.py:180
           ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[13:57:24] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-12-16-26">2022-04-12</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-12 16:26:56.959685</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-12 16:26:59.282831</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 31, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[16:26:56] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:26
[16:26:57] Deleting existing data...                                 base.py:228
           Getting all files in NTL...                               base.py:180
           ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[16:26:58] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
[16:26:59] HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:35
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  


  <h2 id="2022-04-11-13-07">2022-04-11</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-11 13:07:53.760104</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-11 13:07:56.182203</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 31, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.npt.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:07:53] Fetching Scraper for: NTL                              handlers.py:23
           Begin attempting to scrape: NTL                        handlers.py:26
           Deleting existing data...                                 base.py:228
[13:07:54] Getting all files in NTL...                               base.py:180
           ...found 1 files in NTL                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[13:07:55] ...data deleted.                                          base.py:235
           Scraping from https://democracy.npt.gov.uk/mgWebService.as base.py:40
           mx/GetCouncillorsByWard                                              
           HTTPSConnectionPool(host='democracy.npt.gov.uk',       handlers.py:35
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[13:07:56] Finished attempting to scrape: NTL                        base.py:313
</pre>
  

  

  

  

  


      </main>
      <footer class="ds-footer">...</footer>
    </div>
  </body>
