<!doctype html>
<html>
  <head>
    <title>LGSF Dashboard</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <link rel="shortcut icon" href="https://democracyclub.org.uk/static/images/logo_icon.png">
  </head>
  <body>
    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  


  <h2 id="2023-03-13-15-16">2023-03-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-03-13 15:16:28.595362</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-03-13 15:16:31.002371</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[15:16:28] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[15:16:29] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[15:16:30] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[15:16:31] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-03-06-14-06">2023-03-06</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-03-06 14:06:24.621608</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-03-06 14:06:27.608133</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:06:24] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[14:06:25] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:06:26] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
[14:06:27] HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-02-27-13-27">2023-02-27</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-02-27 13:27:21.188498</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-02-27 13:27:23.565460</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:27:21] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:27:22] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:27:23] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-02-20-13-55">2023-02-20</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-02-20 13:55:36.339263</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-02-20 13:55:38.765906</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:55:36] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:55:37] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:55:38] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-02-13-14-53">2023-02-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-02-13 14:53:46.272909</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-02-13 14:53:49.095028</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:53:46] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[14:53:47] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:53:48] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[14:53:49] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-02-06-14-49">2023-02-06</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-02-06 14:49:07.161069</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-02-06 14:49:09.627229</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:49:07] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
[14:49:08] ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:49:09] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-01-30-13-15">2023-01-30</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-01-30 13:15:47.504666</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-01-30 13:15:50.105809</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:15:47] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:15:48] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:15:49] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[13:15:50] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-01-23-13-38">2023-01-23</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-01-23 13:38:46.582979</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-01-23 13:38:48.935844</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:38:46] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:38:47] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:38:48] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-01-16-14-35">2023-01-16</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-01-16 14:35:10.682275</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-01-16 14:35:13.190323</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:35:10] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
[14:35:11] Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:35:12] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[14:35:13] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-01-09-13-13">2023-01-09</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-01-09 13:13:53.556936</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-01-09 13:13:56.984394</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:13:53] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
[13:13:54] Deleting existing data...                                 base.py:239
[13:13:55] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:13:56] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-01-02-14-27">2023-01-02</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-01-02 14:27:48.764949</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-01-02 14:27:51.154706</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:27:48] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
[14:27:49] Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:27:50] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[14:27:51] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-12-26-13-39">2022-12-26</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-12-26 13:39:27.461416</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-12-26 13:39:29.813872</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:39:27] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:39:28] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:39:29] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-12-19-14-01">2022-12-19</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-12-19 14:01:51.567138</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-12-19 14:01:53.946458</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:01:51] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[14:01:52] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:01:53] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-12-12-13-57">2022-12-12</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-12-12 13:57:29.303537</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-12-12 13:57:32.555617</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:57:29] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:57:30] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:57:32] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-12-05-13-59">2022-12-05</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-12-05 13:59:42.021211</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-12-05 13:59:44.452891</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:59:42] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
[13:59:43] ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
           ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[13:59:44] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-11-28-13-44">2022-11-28</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-11-28 13:44:52.522297</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-11-28 13:44:54.843345</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:44:52] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:44:53] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:44:54] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-11-21-14-01">2022-11-21</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-11-21 14:01:20.225787</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-11-21 14:01:22.880903</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:01:20] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[14:01:21] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:01:22] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-11-14-13-57">2022-11-14</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-11-14 13:57:15.000720</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-11-14 13:57:18.502329</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:57:15] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
[13:57:16] ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
           ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
[13:57:18] HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-11-07-13-41">2022-11-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-11-07 13:41:13.145024</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-11-07 13:41:15.692646</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:41:13] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:41:14] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:41:15] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2022-10-31-15-15">2022-10-31</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-10-31 15:15:43.127263</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-10-31 15:15:45.610576</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 173, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 190, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[15:15:43] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
[15:15:44] ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[15:15:45] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  


      </main>
      <footer class="ds-footer">
        <div class="ds-block-centered ds-text-centered ds-stack">
          <div class="ds-cluster-center">
            <ul>
              <li><a href="/lgsf-dashboard/api/failing.json">Failing JSON</a></li>
            </ul>
          </div>
          <div class="ds-copyright">
            <a href="https://democracyclub.org.uk/">
              <img src="https://DemocracyClub.github.io/design-system/images/logo_white_text.svg" alt="Democracy Club Home" />
            </a>
            <p>Copyright © 2021 Democracy Club</p>
            <p>Community Interest Company</p>
            <p>Company No: <a href="https://beta.companieshouse.gov.uk/company/09461226">09461226</a></p>
          </div>
        </div>
      </footer>
    </div>
  </body>
