<!doctype html>
<html>
  <head>
    <title>LGSF Dashboard</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <link rel="shortcut icon" href="https://democracyclub.org.uk/static/images/logo_icon.png">
  </head>
  <body>
    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  


  <h2 id="2024-02-11-09-56">2024-02-11</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-11 09:56:16.598024</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-11 09:56:22.456142</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:56:16] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[09:56:17] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
[09:56:18] ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:56:21] Committing batch 1 consisting of 78 files                 base.py:291
[09:56:22] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-10-09-24">2024-02-10</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-10 09:24:14.335662</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-10 09:24:20.151707</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:24:14] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[09:24:15] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[09:24:16] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:24:18] Committing batch 1 consisting of 78 files                 base.py:291
[09:24:20] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-09-10-14">2024-02-09</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-09 10:14:40.051420</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-09 10:14:45.746270</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:14:40] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
[10:14:41] Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[10:14:42] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:14:44] Committing batch 1 consisting of 78 files                 base.py:291
[10:14:45] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-08-09-39">2024-02-08</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-08 09:39:57.627952</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-08 09:40:03.299603</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:39:57] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[09:39:58] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[09:39:59] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:40:02] Committing batch 1 consisting of 78 files                 base.py:291
[09:40:03] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-07-08-58">2024-02-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-07 08:58:25.847368</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-07 08:58:31.533018</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:58:25] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[08:58:26] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
[08:58:27] ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:58:30] Committing batch 1 consisting of 78 files                 base.py:291
[08:58:31] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-06-09-22">2024-02-06</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-06 09:22:17.003669</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-06 09:22:24.442202</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:22:17] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
[09:22:18] Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[09:22:19] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:22:23] Committing batch 1 consisting of 78 files                 base.py:291
[09:22:24] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-05-08-47">2024-02-05</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-05 08:47:49.519094</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-05 08:47:55.198270</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:47:49] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[08:47:50] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[08:47:51] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:47:54] Committing batch 1 consisting of 78 files                 base.py:291
[08:47:55] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-04-10-12">2024-02-04</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-04 10:12:02.564238</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-04 10:12:08.428651</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:12:02] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[10:12:03] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
[10:12:04] ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:12:07] Committing batch 1 consisting of 78 files                 base.py:291
[10:12:08] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-03-09-54">2024-02-03</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-03 09:54:21.024038</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-03 09:54:28.558643</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:54:21] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
[09:54:22] Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[09:54:25] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:54:27] Committing batch 1 consisting of 78 files                 base.py:291
[09:54:28] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-02-08-24">2024-02-02</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-02 08:24:49.324262</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-02 08:24:55.099091</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:24:49] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[08:24:50] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[08:24:51] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:24:53] Committing batch 1 consisting of 78 files                 base.py:291
[08:24:55] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-02-01-08-50">2024-02-01</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-02-01 08:50:45.484450</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-02-01 08:50:50.882763</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:50:45] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[08:50:46] Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[08:50:47] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:50:49] Committing batch 1 consisting of 78 files                 base.py:291
[08:50:50] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-31-08-56">2024-01-31</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>133 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-31 08:56:02.841940</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-31 08:58:16.036137</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f487ab41450>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f487ab41450>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f487ab41450>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:56:02] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[08:56:03] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[08:56:04] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:58:15] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f487ab41450>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
[08:58:16] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-30-09-59">2024-01-30</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-30 09:59:06.662460</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-30 10:01:18.249989</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f88ae259690>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f88ae259690>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f88ae259690>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:59:06] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:59:07] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[09:59:08] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:01:17] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f88ae259690>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
[10:01:18] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-29-10-05">2024-01-29</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>133 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-29 10:05:46.612412</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-29 10:07:59.632884</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7feb92e9bcd0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb92e9bcd0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feb92e9bcd0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:05:46] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[10:05:48] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
[10:05:49] ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:07:59] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7feb92e9bcd0>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-28-09-35">2024-01-28</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-28 09:35:32.906448</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-28 09:37:44.626345</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fd62e1b7160>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd62e1b7160>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd62e1b7160>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:35:32] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:35:33] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[09:35:34] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:37:44] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7fd62e1b7160>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-27-08-38">2024-01-27</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>132 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-27 08:38:22.182437</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-27 08:40:35.071359</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f678a8a9f00>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f678a8a9f00>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f678a8a9f00>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:38:22] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
[08:38:23] ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:40:34] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f678a8a9f00>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
[08:40:35] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-26-09-20">2024-01-26</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>132 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-26 09:20:44.665021</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-26 09:22:56.978207</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f3a0f66eb90>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3a0f66eb90>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3a0f66eb90>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:20:44] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:20:45] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[09:20:46] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:22:56] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f3a0f66eb90>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-25-10-31">2024-01-25</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>132 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-25 10:31:52.278469</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-25 10:34:04.428430</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f7c3a28e350>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7c3a28e350>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7c3a28e350>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:31:52] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[10:31:53] Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[10:31:54] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:34:04] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f7c3a28e350>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-24-08-55">2024-01-24</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-24 08:55:40.886501</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-24 08:57:52.704681</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fece1791ea0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fece1791ea0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fece1791ea0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:55:40] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[08:55:41] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
[08:55:42] Deleting batch no. 1 consisting of 1 files                base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:57:52] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7fece1791ea0>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-23-10-02">2024-01-23</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-23 10:02:19.950309</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-23 10:04:31.873508</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7ff7a5b71060>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff7a5b71060>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff7a5b71060>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:02:19] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[10:02:20] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[10:02:21] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:04:31] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7ff7a5b71060>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  


      </main>
      <footer class="ds-footer">
        <div class="ds-block-centered ds-text-centered ds-stack">
          <div class="ds-cluster-center">
            <ul>
              <li><a href="/lgsf-dashboard/api/failing.json">Failing JSON</a></li>
            </ul>
          </div>
          <div class="ds-copyright">
            <a href="https://democracyclub.org.uk/">
              <img src="https://DemocracyClub.github.io/design-system/images/logo_white_text.svg" alt="Democracy Club Home" />
            </a>
            <p>Copyright © 2021 Democracy Club</p>
            <p>Community Interest Company</p>
            <p>Company No: <a href="https://beta.companieshouse.gov.uk/company/09461226">09461226</a></p>
          </div>
        </div>
      </footer>
    </div>
  </body>
