<!doctype html>
<html>
  <head>
    <title>LGSF Dashboard</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <link rel="shortcut icon" href="https://democracyclub.org.uk/static/images/logo_icon.png">
  </head>
  <body>
    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  


  <h2 id="2024-01-28-09-35">2024-01-28</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-28 09:35:32.906448</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-28 09:37:44.626345</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fd62e1b7160>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd62e1b7160>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd62e1b7160>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:35:32] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:35:33] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[09:35:34] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:37:44] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7fd62e1b7160>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-27-08-38">2024-01-27</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>132 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-27 08:38:22.182437</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-27 08:40:35.071359</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f678a8a9f00>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f678a8a9f00>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f678a8a9f00>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:38:22] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
[08:38:23] ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:40:34] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f678a8a9f00>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
[08:40:35] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-26-09-20">2024-01-26</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>132 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-26 09:20:44.665021</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-26 09:22:56.978207</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f3a0f66eb90>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3a0f66eb90>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3a0f66eb90>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:20:44] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:20:45] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[09:20:46] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:22:56] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f3a0f66eb90>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-25-10-31">2024-01-25</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>132 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-25 10:31:52.278469</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-25 10:34:04.428430</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f7c3a28e350>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7c3a28e350>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7c3a28e350>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:31:52] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[10:31:53] Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[10:31:54] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:34:04] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f7c3a28e350>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-24-08-55">2024-01-24</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-24 08:55:40.886501</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-24 08:57:52.704681</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fece1791ea0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fece1791ea0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fece1791ea0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:55:40] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[08:55:41] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
[08:55:42] Deleting batch no. 1 consisting of 1 files                base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:57:52] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7fece1791ea0>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-23-10-02">2024-01-23</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-23 10:02:19.950309</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-23 10:04:31.873508</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7ff7a5b71060>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff7a5b71060>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff7a5b71060>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:02:19] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[10:02:20] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[10:02:21] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:04:31] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7ff7a5b71060>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-22-09-53">2024-01-22</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>132 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-22 09:53:28.809828</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-22 09:55:40.829511</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fb2da0ab580>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb2da0ab580>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb2da0ab580>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:53:28] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:53:29] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[09:53:30] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:55:40] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7fb2da0ab580>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-21-09-45">2024-01-21</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>132 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-21 09:45:10.804879</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-21 09:47:23.141958</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f3fe80fc790>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3fe80fc790>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3fe80fc790>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:45:10] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:45:11] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[09:45:12] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:47:22] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f3fe80fc790>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
[09:47:23] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-20-09-28">2024-01-20</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-20 09:28:05.207618</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-20 09:30:16.956281</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fe9062efee0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe9062efee0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe9062efee0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:28:05] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[09:28:06] Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[09:28:07] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:30:16] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7fe9062efee0>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-19-08-58">2024-01-19</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>131 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-19 08:58:12.277297</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-19 09:00:23.926841</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7faf7b00a380>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7faf7b00a380>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7faf7b00a380>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:58:12] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[08:58:13] Getting all files in Councillors...                       base.py:203
           ...found 1 files in Councillors                           base.py:219
           Deleting batch no. 1 consisting of 1 files                base.py:230
[08:58:14] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:00:23] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7faf7b00a380>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-18-10-40">2024-01-18</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>133 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-18 10:40:12.570986</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-18 10:42:25.843855</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/python/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/python/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/opt/python/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/var/lang/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/python/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/opt/python/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f822eaefbb0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f822eaefbb0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 200, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 219, in get_councillors
    req = self.get(
  File "/var/task/lgsf/scrapers/base.py", line 47, in get
    response = self.requests_session.get(
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='democracy.canterbury.gov.uk', port=80): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f822eaefbb0>, 'Connection to democracy.canterbury.gov.uk timed out. (connect timeout=None)'))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:40:12] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[10:40:13] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[10:40:14] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:42:25] HTTPConnectionPool(host='democracy.canterbury.gov.uk', handlers.py:36
           port=80): Max retries exceeded with url:                             
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           ConnectTimeoutError(<urllib3.connection.HTTPConnection               
           object at 0x7f822eaefbb0>, 'Connection to                            
           democracy.canterbury.gov.uk timed out. (connect                      
           timeout=None)'))                                                     
           Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-17-08-28">2024-01-17</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>6 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-17 08:28:05.876095</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-17 08:28:12.356943</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:28:05] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[08:28:06] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
[08:28:07] ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:28:11] Committing batch 1 consisting of 78 files                 base.py:291
[08:28:12] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-16-09-26">2024-01-16</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-16 09:26:01.893580</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-16 09:26:09.221974</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:26:01] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:26:03] Deleting existing data...                                 base.py:251
[09:26:04] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[09:26:05] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:26:08] Committing batch 1 consisting of 78 files                 base.py:291
[09:26:09] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-15-10-28">2024-01-15</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>6 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-15 10:28:14.087223</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-15 10:28:21.078629</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:28:14] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
[10:28:15] Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[10:28:16] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:28:19] Committing batch 1 consisting of 78 files                 base.py:291
[10:28:21] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-14-08-24">2024-01-14</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>6 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-14 08:24:28.520235</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-14 08:24:34.784893</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:24:28] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[08:24:29] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[08:24:30] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:24:33] Committing batch 1 consisting of 78 files                 base.py:291
[08:24:34] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-13-10-28">2024-01-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-13 10:28:11.270292</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-13 10:28:19.916439</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:28:11] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
           Deleting existing data...                                 base.py:251
[10:28:12] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[10:28:13] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:28:17] Committing batch 1 consisting of 78 files                 base.py:291
[10:28:19] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-12-08-58">2024-01-12</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-12 08:58:40.858319</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-12 08:58:48.784062</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:58:40] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[08:58:41] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
[08:58:42] Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[08:58:47] Committing batch 1 consisting of 78 files                 base.py:291
[08:58:48] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-11-10-31">2024-01-11</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>6 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-11 10:31:48.923383</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-11 10:31:55.437946</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:31:48] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[10:31:49] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
[10:31:50] ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[10:31:51] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:31:54] Committing batch 1 consisting of 78 files                 base.py:291
[10:31:55] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-10-09-26">2024-01-10</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-10 09:26:03.770299</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-10 09:26:11.643487</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:26:03] Fetching Scraper for: CAT                              handlers.py:23
           Begin attempting to scrape: CAT                        handlers.py:27
[09:26:04] Deleting existing data...                                 base.py:251
           Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
[09:26:05] Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
           ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[09:26:10] Committing batch 1 consisting of 78 files                 base.py:291
[09:26:11] Finished attempting to scrape: CAT                        base.py:339
</pre>
  

  


  <h2 id="2024-01-09-10-16">2024-01-09</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>12 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2024-01-09 10:16:44.816103</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2024-01-09 10:16:57.450575</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:16:44] Fetching Scraper for: CAT                              handlers.py:23
[10:16:49] Begin attempting to scrape: CAT                        handlers.py:27
[10:16:51] Deleting existing data...                                 base.py:251
[10:16:52] Getting all files in Councillors...                       base.py:203
           Getting all files in Councillors/json...                  base.py:203
           ...found 39 files in Councillors/json                     base.py:219
           Getting all files in Councillors/raw...                   base.py:203
           ...found 39 files in Councillors/raw                      base.py:219
           ...found 79 files in Councillors                          base.py:219
           Deleting batch no. 1 consisting of 79 files               base.py:230
[10:16:53] ...data deleted.                                          base.py:258
           Scraping from                                              base.py:41
           http://democracy.canterbury.gov.uk/mgWebService.asmx/GetCo           
           uncillorsByWard                                                      
[10:16:56] Committing batch 1 consisting of 78 files                 base.py:291
[10:16:57] Finished attempting to scrape: CAT                        base.py:339
</pre>
  


      </main>
      <footer class="ds-footer">
        <div class="ds-block-centered ds-text-centered ds-stack">
          <div class="ds-cluster-center">
            <ul>
              <li><a href="/lgsf-dashboard/api/failing.json">Failing JSON</a></li>
            </ul>
          </div>
          <div class="ds-copyright">
            <a href="https://democracyclub.org.uk/">
              <img src="https://DemocracyClub.github.io/design-system/images/logo_white_text.svg" alt="Democracy Club Home" />
            </a>
            <p>Copyright © 2021 Democracy Club</p>
            <p>Community Interest Company</p>
            <p>Company No: <a href="https://beta.companieshouse.gov.uk/company/09461226">09461226</a></p>
          </div>
        </div>
      </footer>
    </div>
  </body>
